Repository FromDoppler/tdd-katas, pull requests merged in 2022-06, with the labels that each got.

#7 Cromero - stringCalculator
  .gitignore
  src/cromero/StringCalculator.test.ts
  src/cromero/StringCalculator.ts
Labels: size/M

#6 Kata 2 string calculator
  src/bruno/StringCalculator.test.ts
  src/bruno/StringCalculator.ts
Labels: size/L

#2 Greeter kata mauro
  src/Mauro/Greeter.test.ts
  src/Mauro/Greeter.ts
  src/_copy_me/Greeter.test.ts
  src/_copy_me/Greeter.ts
Labels: size/M

#12 build: fix editorconfig for md
  .editorconfig
Labels: size/XS

#11 test: remove slow test
  src/andresmoschini/PrimeFactors.test.ts
Labels: size/XS
